#!/usr/bin/env node
/**
 * Tridente de Memoria — Generador de documentación (SSOT → artefactos).
 *
 * Lee `protocol/tridente.spec.json` y regenera TODOS los archivos derivados:
 * AGENTS.md, SKILL.md, plantillas, adaptadores por herramienta y los bloques
 * marcados dentro de los README.
 *
 *   node scripts/sync.mjs           escribe los archivos
 *   node scripts/sync.mjs --check   no escribe; sale 1 si algo está desincronizado
 *
 * Sin dependencias externas: sólo Node >= 18.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPEC_PATH = join(ROOT, 'protocol', 'tridente.spec.json');
const spec = JSON.parse(readFileSync(SPEC_PATH, 'utf8'));

const CHECK = process.argv.includes('--check');
// Cabecera de archivo generado. Va envuelta en marcadores para que
// init-tridente.* pueda retirarla al copiar el archivo a otro proyecto.
const HDR_OPEN = '<!-- tridente:header-start -->';
const HDR_CLOSE = '<!-- tridente:header-end -->';
const BANNER_ES = `${HDR_OPEN}
<!-- GENERADO POR scripts/sync.mjs — NO EDITAR A MANO.
     Fuente de verdad: protocol/tridente.spec.json
     Regenerar con: node scripts/sync.mjs -->
${HDR_CLOSE}`;
const BANNER_EN = `${HDR_OPEN}
<!-- GENERATED BY scripts/sync.mjs — DO NOT EDIT BY HAND.
     Source of truth: protocol/tridente.spec.json
     Regenerate with: node scripts/sync.mjs -->
${HDR_CLOSE}`;

// ---------------------------------------------------------------- utilidades

const byId = Object.fromEntries(spec.files.map((f) => [f.id, f]));
const readFiles = spec.readOrder.map((id) => byId[id]);
const writeFiles = spec.writeOrder.map((id) => byId[id]);
const names = spec.files.map((f) => f.filename);

/** Normaliza saltos de línea para que la comparación no dependa del SO. */
const norm = (s) => s.replace(/\r\n/g, '\n').replace(/[ \t]+$/gm, '').trimEnd() + '\n';

/** Resuelve {dna}/{plan}/{lessons} a los nombres reales del spec. */
function interp(text) {
  return String(text).replace(/\{(dna|plan|lessons)\}/g, (_m, id) => byId[id].filename);
}

/** Bloque de código markdown para un formato de entrada del spec. */
function entryBlock(entry, lang = 'es') {
  const key = lang === 'en' ? 'keyEn' : 'key';
  const hint = lang === 'en' ? 'hintEn' : 'hint';
  const head = entry.headingTemplate
    .replace('{date}', spec.dateFormat.display)
    .replace('{title}', lang === 'en' ? '[Title]' : '[Título]');
  const lines = entry.fields.map(
    (f) => `- **${f[key]}:** [${interp(f[hint])}]${f.required ? '' : ' *(opcional)*'}`,
  );
  return ['```markdown', head, ...lines, '```'].join('\n');
}

/** Tabla markdown a partir de cabeceras y filas. */
function table(headers, rows, align) {
  const sep = headers.map((_, i) => align?.[i] ?? ':---');
  return [
    `| ${headers.join(' | ')} |`,
    `| ${sep.join(' | ')} |`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ].join('\n');
}

// ------------------------------------------------------- bloques compartidos

/** Tabla de los 3 archivos maestros (usada en README, AGENTS y SKILL). */
function tridentTable(lang = 'es') {
  const en = lang === 'en';
  return table(
    en ? ['File', 'Role', 'Contents'] : ['Archivo', 'Rol', 'Contenido'],
    spec.files.map((f) => [
      `\`${f.filename}\``,
      `${f.emoji} ${en ? f.roleEn : f.role}`,
      en ? f.purposeEn : f.purpose,
    ]),
  );
}

/** Tabla de compatibilidad por herramienta. */
function adapterTable(lang = 'es') {
  const en = lang === 'en';
  const seen = new Set();
  const rows = [];
  for (const a of spec.adapters) {
    const k = a.tool + a.path;
    if (seen.has(k)) continue;
    seen.add(k);
    const mech =
      a.kind === 'native'
        ? en
          ? 'Native'
          : 'Nativo'
        : en
          ? 'Generated adapter'
          : 'Adaptador generado';
    // Algunas herramientas necesitan un paso extra: decirlo aquí evita anunciar
    // como automático algo que no lo es.
    const caveat = a.manual ? (en ? ` — ${a.manualEn}` : ` — ${a.manual}`) : '';
    rows.push([a.tool, `\`${a.path}\``, mech + caveat]);
  }
  return table(en ? ['Tool', 'File it reads', 'Mechanism'] : ['Herramienta', 'Archivo que lee', 'Mecanismo'], rows);
}

/** Tabla de rutas de instalación del skill. */
function installTable(lang = 'es') {
  const en = lang === 'en';
  return table(
    en ? ['Platform', 'Install path'] : ['Plataforma', 'Ruta de instalación'],
    spec.skillInstallPaths.map((p) => [`**${p.platform}**`, `\`${p.path}\``]),
  );
}

// ------------------------------------------------------------- AGENTS.md (ES)

function buildAgents() {
  const d = spec.dateFormat;
  return `${BANNER_ES}

# Instrucciones para agentes de IA

Este proyecto opera bajo el protocolo **${spec.protocol.name}** (v${spec.protocol.version}).
Tu misión: mantener el contexto completo del proyecto y no reintroducir errores ya resueltos.

> **Regla de oro: ${spec.protocol.goldenRule}**

> 🇬🇧 English version: [\`docs/AGENTS.en.md\`](docs/AGENTS.en.md)

---

## 1. Los tres archivos maestros

${tridentTable('es')}

Los nombres son canónicos. Si un proyecto ya usa alias (${spec.files
    .flatMap((f) => f.aliases)
    .slice(0, 4)
    .map((a) => `\`${a}\``)
    .join(', ')}…), identifícalos **por su función**, no sólo por el nombre.

---

## 2. Antes de escribir código — LEER

Lee los tres archivos en este orden y no empieces hasta terminarlos:

${table(
  ['#', 'Archivo', 'Qué extraer'],
  readFiles.map((f, i) => [String(i + 1), `\`${f.filename}\``, f.extract]),
  [':---:', ':---', ':---'],
)}

- Si **falta alguno** → detente y ejecuta la **Fase Cero** (sección 5). No inventes el contenido.
- Si el contenido **contradice** lo que te pide el usuario → dilo antes de programar, no después.
- Si un requisito es **ambiguo** → pregunta. No asumas.

---

## 3. Durante la tarea

- **Bug o trampa descubierta** → anótala; irá a \`${byId.lessons.filename}\` al cerrar.
- **Decisión de arquitectura** → anótala; irá a la Bitácora de \`${byId.plan.filename}\`.
- **No** edites los archivos maestros a mitad de tarea salvo que la tarea sea precisamente esa.

---

## 4. Al terminar — ESCRIBIR en el orden sagrado

${writeFiles.map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.purpose}`).join('\n')}

> ${spec.writeOrderRationale}

### Formato de lección (\`${byId.lessons.filename}\` → ${spec.entries.lesson.section})

${entryBlock(spec.entries.lesson, 'es')}

### Formato de decisión (\`${byId.plan.filename}\` → ${spec.entries.decision.section})

${entryBlock(spec.entries.decision, 'es')}

### Formato de mina activa (\`${byId.lessons.filename}\` → ${spec.entries.mine.section})

${table(spec.entries.mine.table.columns, [
  ['[Componente]', '[Qué rompe y cuándo]', spec.entries.mine.table.states.map((s) => `${s.emoji} ${s.label}`).join(' / ')],
])}

${spec.entries.mine.table.states.map((s) => `- ${s.emoji} **${s.label}** — ${s.meaning}`).join('\n')}

### Formato de fecha — obligatorio

Todas las fechas usan **${d.display}** (ISO 8601). Ejemplo: \`${d.example}\`.
${d.rationale}

---

## 5. Fase Cero (inicialización)

Cuando el usuario pide *"instala el Tridente"* / *"inicia un proyecto con el Tridente"* y los archivos no existen:

1. **Con terminal** → \`bash init-tridente.sh\` (Unix/WSL/Git Bash) o \`powershell -ExecutionPolicy Bypass -File init-tridente.ps1\` (Windows).
2. **Sin terminal** → haz estas preguntas, una por una, y espera la respuesta:
${spec.init.tokens
    .filter((t) => t.question)
    .map((t, i) => `   ${i + 1}. ${t.question}`)
    .join('\n')}
   Después crea los tres archivos a partir de \`templates/\`, sustituyendo cada token \`{{...}}\`.
3. **Nunca** crees archivos vacíos ni inventes datos del proyecto.

Al terminar, deja \`AGENTS.md\` en la raíz del proyecto.

---

## 6. Regla de interconexión

Los tres archivos son **un solo organismo**, no tres documentos sueltos:

- Decisión de diseño en \`${byId.plan.filename}\` → refléjala en \`${byId.dna.filename}\`.
- Trampa técnica al implementar → crúzala en \`${byId.lessons.filename}\`.
- Cambio de stack → ADN + bitácora + lección (si aplica).

Una entrada que no enlaza con las otras dos es una entrada huérfana: **el tridente se desincroniza justo ahí**.

---

## 7. Verificación

Antes de dar por cerrada una tarea que tocó los archivos maestros:

\`\`\`bash
node scripts/validate.mjs
\`\`\`

El validador comprueba nombres, secciones, orden, formato de fecha y enlaces cruzados, y devuelve un puntaje 0–100.

---

## 8. Compatibilidad entre herramientas

\`AGENTS.md\` es la **única fuente** de estas instrucciones. El resto de archivos de configuración de agentes son punteros generados que reenvían aquí.

${adapterTable('es')}

**No edites los punteros a mano.** Edita \`protocol/tridente.spec.json\` y ejecuta \`node scripts/sync.mjs\`.
`;
}

// -------------------------------------------------------- docs/AGENTS.en.md

function buildAgentsEn() {
  const d = spec.dateFormat;
  return `${BANNER_EN}

# Instructions for AI agents

This project runs the **${spec.protocol.nameEn}** protocol (v${spec.protocol.version}).
Your mission: keep full project context and never reintroduce an already-solved bug.

> **Golden rule: ${spec.protocol.goldenRuleEn}**

> 🇪🇸 Versión en español (canónica): [\`AGENTS.md\`](../AGENTS.md)

---

## 1. The three master files

${tridentTable('en')}

Names are canonical. If a project already uses aliases, identify the files **by role**, not by name alone.

---

## 2. Before writing code — READ

${table(
  ['#', 'File', 'What to extract'],
  readFiles.map((f, i) => [String(i + 1), `\`${f.filename}\``, f.extractEn]),
  [':---:', ':---', ':---'],
)}

- **Any file missing** → stop and run Phase Zero (section 5). Do not invent content.
- **Content contradicts the request** → say so before coding, not after.
- **Ambiguous requirement** → ask. Do not assume.

---

## 3. During the task

- **Bug or trap found** → note it; it goes to \`${byId.lessons.filename}\` at close.
- **Architectural decision** → note it; it goes to the decision log in \`${byId.plan.filename}\`.

---

## 4. When done — WRITE in the sacred order

${writeFiles.map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.purposeEn}`).join('\n')}

### Lesson format

${entryBlock(spec.entries.lesson, 'en')}

### Decision format

${entryBlock(spec.entries.decision, 'en')}

### Date format — mandatory

All dates use **${d.display}** (ISO 8601). Example: \`${d.example}\`.

---

## 5. Phase Zero (initialization)

1. **With a terminal** → \`bash init-tridente.sh\` or \`powershell -ExecutionPolicy Bypass -File init-tridente.ps1\`.
2. **Without a terminal** → ask these questions one at a time, then create the files from \`templates/\`:
${spec.init.tokens.filter((t) => t.question).map((t, i) => `   ${i + 1}. ${t.question}`).join('\n')}
3. **Never** create empty files or invent project details.

---

## 6. Interconnection rule

The three files are **one organism**. An entry that does not link to the other two is an orphan — that is exactly where the trident desynchronizes.

---

## 7. Verification

\`\`\`bash
node scripts/validate.mjs
\`\`\`

---

## 8. Tool compatibility

${adapterTable('en')}

Do not edit the pointer files by hand. Edit \`protocol/tridente.spec.json\` and run \`node scripts/sync.mjs\`.
`;
}

// ------------------------------------------------------------------ SKILL.md

function buildSkill() {
  const description =
    'Sistema de memoria persistente basado en 3 archivos interconectados ' +
    `(${names.join(', ')}). Inicializa proyectos con entrevista interactiva (Fase Cero) ` +
    'y se usa SIEMPRE antes de escribir o modificar código para mantener el contexto. ' +
    'Compatible con Claude Code, Codex, Cursor, Gemini, Copilot y agentes autónomos.';

  return `---
name: ${spec.protocol.id}
description: ${description}
license: ${spec.protocol.license}
metadata:
  version: ${spec.protocol.version}
  repository: ${spec.protocol.repository}
---

${BANNER_ES}

# 🔱 ${spec.protocol.name} (${spec.protocol.nameEn})

Protocolo de **memoria persistente compartida** que mantiene sincronizado el contexto de los agentes de IA a lo largo del tiempo.

> **${spec.protocol.goldenRule}**

## Cuándo usar este skill

- El usuario pide **iniciar un proyecto** con memoria persistente.
- El usuario dice **"instala el Tridente"**, **"Memory Trident"** o equivalente.
- Vas a **modificar código** y existen (o deberían existir) los tres archivos maestros.
- El usuario pregunta **cómo mantener contexto** entre sesiones de IA.
- Detectas que el proyecto **no tiene reglas documentadas** y el agente está adivinando.

## Los tres archivos maestros

${tridentTable('es')}

**Alias:** ${spec.files
    .map((f) => `\`${f.filename}\` (≈ ${f.aliases.map((a) => `\`${a}\``).join(', ')})`)
    .join(' · ')}. Identifica por función, no por nombre.

## Protocolo de lectura

${readFiles.map((f, i) => `${i + 1}. \`${f.filename}\` — ${f.extract}`).join('\n')}

## Protocolo de escritura (orden sagrado)

${writeFiles.map((f, i) => `${i + 1}. \`${f.filename}\` — ${f.purpose}`).join('\n')}

> ${spec.writeOrderRationale}

### Formatos de entrada

${entryBlock(spec.entries.lesson, 'es')}

${entryBlock(spec.entries.decision, 'es')}

Fechas en **${spec.dateFormat.display}** (ISO 8601), p. ej. \`${spec.dateFormat.example}\`.

## Fase Cero

Si los tres archivos **no existen**, está **prohibido** crearlos vacíos o inventar el proyecto.

\`\`\`bash
bash init-tridente.sh                 # Unix / WSL / Git Bash
bash init-tridente.sh --help          # modo no interactivo y banderas
\`\`\`

\`\`\`powershell
powershell -ExecutionPolicy Bypass -File init-tridente.ps1
\`\`\`

Sin terminal, haz la entrevista y puebla las plantillas de \`templates/\`:

${spec.init.tokens.filter((t) => t.question).map((t, i) => `${i + 1}. ${t.question}`).join('\n')}

## Verificación

\`\`\`bash
node scripts/validate.mjs     # puntaje 0–100 de salud del Tridente
node scripts/sync.mjs --check # comprueba que la documentación no se desincronizó
\`\`\`

## Instalación

${installTable('es')}

\`\`\`bash
git clone ${spec.protocol.repository} ~/.claude/skills/${spec.protocol.id}
\`\`\`

> El directorio de destino **debe** llamarse \`${spec.protocol.id}\` para que coincida con el campo \`name\` del frontmatter.

Repositorio: ${spec.protocol.repository}
`;
}

// ----------------------------------------------------------------- plantillas

function buildTemplate(file) {
  const h = (s) => `## ${s.emoji} ${s.heading}`;
  const others = spec.files.filter((f) => f.id !== file.id);
  const head = `${HDR_OPEN}
<!-- GENERADO POR scripts/sync.mjs — NO EDITAR A MANO.
     Fuente de verdad: protocol/tridente.spec.json
     Plantilla con tokens {{...}}: los rellenan init-tridente.sh / init-tridente.ps1.
     Si la copias a mano, sustituye cada token por tu texto. -->
${HDR_CLOSE}

# ${file.emoji} ${file.role}: {{PROJECT_NAME}}

> Archivo maestro ${file.index}/${spec.files.length} del ${spec.protocol.name}. ${file.purpose}
> Ver también: ${others.map((o) => `\`${o.filename}\` (${o.role})`).join(' · ')}
> Fechas en ${spec.dateFormat.display} (ISO 8601).
`;

  const bodies = {
    dna: () => `
${h(file.sections[0])}

- **Misión:** {{GOAL}}
- **Visión:** [¿Cómo se ve el éxito?]
- **Usuarios objetivo:** [¿Para quién se construye?]

${h(file.sections[1])}

{{STACK}}

${table(['Capa', 'Tecnología'], [
  ['**Frontend**', '[Ej: React, Next.js, Vue]'],
  ['**Backend**', '[Ej: Node.js, Python, Go]'],
  ['**Base de datos**', '[Ej: PostgreSQL, MongoDB, SQLite]'],
  ['**Infraestructura**', '[Ej: AWS, Vercel, Docker]'],
  ['**Herramientas**', '[Ej: pnpm, Turborepo, GitHub Actions]'],
])}

${h(file.sections[2])}

1. {{RULES}}
2. [Regla 2 — Ej: "No añadir dependencias sin aprobación"]
3. Seguir el protocolo del ${spec.protocol.name}: leer los ${spec.files.length} archivos antes de escribir código.
4. Fechas en ${spec.dateFormat.display} en todos los archivos maestros.

${h(file.sections[3])}

- **Patrón de diseño:** [Ej: Clean Architecture, MVC, monorepo]
- **Convención de nombres:** [Ej: camelCase variables, PascalCase clases]
- **Estructura de carpetas:** [Ej: \`src/features/\`, \`src/shared/\`]
- **Tests:** [Ej: cobertura mínima 80 %, Vitest + Testing Library]
- **Commits:** [Ej: Conventional Commits en español]

${h(file.sections[4])}

${others.map((o) => `- ${o.emoji} \`${o.filename}\` — ${o.purpose}`).join('\n')}
`,

    plan: () => `
${h(file.sections[0])}

- **Objetivo:** {{MILESTONE}}
- **Fecha estimada:** [${spec.dateFormat.display}]
- **Criterio de éxito:** [¿Cómo sabemos que está listo?]

${h(file.sections[1])}

- [ ] **Tarea 1:** [Descripción concreta y verificable]
- [ ] **Tarea 2:** [Descripción concreta y verificable]
- [ ] **Tarea 3:** [Descripción concreta y verificable]

${h(file.sections[2])}

- [ ] [Tarea futura 1]
- [ ] [Tarea futura 2]

${h(file.sections[3])}

${spec.entries.decision.headingTemplate
  .replace('{date}', '{{DATE}}')
  .replace('{title}', `Inicialización del ${spec.protocol.name}`)}

- **${spec.entries.decision.fields[0].key}:** Adoptar el ${spec.protocol.name} como memoria persistente del proyecto.
- **${spec.entries.decision.fields[1].key}:** Evitar la pérdida de contexto entre sesiones de IA y las regresiones que provoca.
- **${spec.entries.decision.fields[2].key}:** Se crean los ${spec.files.length} archivos maestros y \`AGENTS.md\` en la raíz.
- **${spec.entries.decision.fields[3].key}:** \`${byId.lessons.filename}\` → ${spec.entries.lesson.section}.

---

*Este archivo se actualiza en ${spec.writeOrder.indexOf(file.id) + 1}.º lugar del orden sagrado.*
`,

    lessons: () => `
${h(file.sections[0])}

${table(spec.entries.mine.table.columns, [
  ['—', 'Aún no se han detectado minas en este proyecto', '🟢 Limpio'],
])}

${spec.entries.mine.table.states.map((s) => `- ${s.emoji} **${s.label}** — ${s.meaning}`).join('\n')}

${h(file.sections[1])}

${spec.entries.lesson.headingTemplate
  .replace('{date}', '{{DATE}}')
  .replace('{title}', 'Proyecto sin memoria persistente')}

- **${spec.entries.lesson.fields[0].key}:** Cada sesión de IA arrancaba sin contexto y reintroducía errores ya resueltos.
- **${spec.entries.lesson.fields[1].key}:** Se instala el ${spec.protocol.name} (${spec.files.length} archivos maestros interconectados).
- **${spec.entries.lesson.fields[2].key}:** Leer los ${spec.files.length} archivos antes de escribir código; escribir en el orden sagrado al terminar.
- **${spec.entries.lesson.fields[3].key}:** Sí — regla añadida en \`${byId.dna.filename}\`.

---

*Este archivo se actualiza en ${spec.writeOrder.indexOf(file.id) + 1}.º lugar: PRIMERO, en cuanto se descubre el bug.*
`,
  };

  if (typeof bodies[file.id] !== 'function') {
    console.error(
      `✗ No hay cuerpo de plantilla para el archivo maestro "${file.id}" (${file.filename}).\n` +
        `  Cada archivo de spec.files necesita su bloque en buildTemplate() de scripts/sync.mjs.\n` +
        `  Definidos hoy: ${Object.keys(bodies).join(', ')}`,
    );
    process.exit(2);
  }
  return head + bodies[file.id]();
}

/** Documentación de los tokens de plantilla. */
function buildTemplatesReadme() {
  return `${BANNER_ES}

# Plantillas del ${spec.protocol.name}

Los ${spec.files.length} archivos maestros en blanco. Contienen **tokens** \`{{...}}\` que rellenan
\`init-tridente.sh\` / \`init-tridente.ps1\`. Si copias una plantilla a mano, sustituye cada token
por tu texto.

Los scripts de inicialización **no contienen** el texto de las plantillas: lo leen de esta carpeta.
Por eso script y plantilla no pueden desincronizarse.

${table(
  ['Token', 'Pregunta de la Fase Cero', 'Aparece en'],
  spec.init.tokens.map((t) => [
    `\`${t.token}\``,
    t.question ?? (t.default === '@today' ? '*(fecha actual, automática)*' : '*(automático)*'),
    t.files.map((id) => `\`${byId[id].filename}\``).join(', '),
  ]),
)}

\`@dirname\` = nombre de la carpeta de destino · \`@today\` = fecha actual en ${spec.dateFormat.display}.

---

*Generado desde \`protocol/tridente.spec.json\`. No editar a mano.*
`;
}

// ---------------------------------------------------------------- adaptadores

const POINTER_ES = (tool, path = 'AGENTS.md') => {
  const depth = path.split('/').length - 1;
  const link = depth ? '../'.repeat(depth) + 'AGENTS.md' : 'AGENTS.md';
  return `${BANNER_ES}

# ${spec.protocol.name} — ${tool}

Las instrucciones operativas de este repositorio viven en un solo sitio: **[\`AGENTS.md\`](${link})**.

**Léelo completo antes de escribir o modificar código.** Este archivo existe únicamente para que ${tool} encuentre el protocolo; no duplica su contenido a propósito, porque la duplicación es lo que desincroniza la documentación.

> ${spec.protocol.goldenRule}

Resumen de un vistazo (el detalle y la autoridad están en \`AGENTS.md\`):

1. **Leer** ${readFiles.map((f) => `\`${f.filename}\``).join(' → ')} antes de tocar código.
2. **Escribir** al terminar en el orden ${writeFiles.map((f) => `\`${f.filename}\``).join(' → ')}.
3. Fechas en \`${spec.dateFormat.display}\`. Nunca crear archivos maestros vacíos.
`;
};

function buildAdapters() {
  const out = {};
  for (const a of spec.adapters) {
    if (a.kind === 'native') continue;
    if (a.kind === 'json-context') {
      const files = ['AGENTS.md', byId.dna.filename];
      out[a.path] =
        JSON.stringify(
          {
            $comment: 'Puntero del Tridente de Memoria: el contexto real vive en AGENTS.md.',
            // Esquema actual de Gemini CLI (ajustes anidados).
            context: { fileName: files },
            // Clave plana heredada, para versiones anteriores. Gemini CLI migra
            // automáticamente la plana a la anidada; mantener ambas evita que la
            // migración reescriba el archivo y dispare una falsa deriva.
            contextFileName: files,
          },
          null,
          2,
        ) + '\n';
      continue;
    }
    if (a.kind === 'mdc') {
      out[a.path] = `---
description: ${spec.protocol.name} — protocolo obligatorio de memoria persistente
alwaysApply: true
---

${POINTER_ES(a.tool, a.path)}`;
      continue;
    }
    if (a.kind === 'import') {
      // La ruta del import debe ser la misma que la del enlace del cuerpo: un
      // archivo que usa dos bases distintas para el mismo destino se contradice.
      const depth = a.path.split('/').length - 1;
      const link = depth ? '../'.repeat(depth) + 'AGENTS.md' : 'AGENTS.md';
      out[a.path] = `${POINTER_ES(a.tool, a.path)}
@${link}
`;
      continue;
    }
    out[a.path] = POINTER_ES(a.tool, a.path);
  }
  return out;
}

// ------------------------------------ AGENTS.md para el proyecto de destino

/**
 * `AGENTS.md` del repositorio del skill habla de `scripts/`, `templates/` y
 * `protocol/`, que NO existen en el proyecto donde se instala. Esta variante
 * sale del mismo spec pero sólo menciona lo que el usuario tendrá delante.
 */
function buildProjectAgents() {
  const d = spec.dateFormat;
  return `${BANNER_ES}

# Instrucciones para agentes de IA

Este proyecto opera bajo el protocolo **${spec.protocol.name}** (v${spec.protocol.version}).
Tu misión: mantener el contexto completo del proyecto y no reintroducir errores ya resueltos.

> **Regla de oro: ${spec.protocol.goldenRule}**

---

## 1. Los tres archivos maestros

${tridentTable('es')}

Los nombres son canónicos. Si este proyecto usa alias (${spec.files
    .flatMap((f) => f.aliases)
    .slice(0, 4)
    .map((a) => `\`${a}\``)
    .join(', ')}…), identifícalos **por su función**, no sólo por el nombre.

---

## 2. Antes de escribir código — LEER

Lee los tres archivos en este orden y no empieces hasta terminarlos:

${table(
  ['#', 'Archivo', 'Qué extraer'],
  readFiles.map((f, i) => [String(i + 1), `\`${f.filename}\``, f.extract]),
  [':---:', ':---', ':---'],
)}

- Si **falta alguno** → detente y ejecuta la **Fase Cero** (sección 5). No inventes el contenido.
- Si el contenido **contradice** lo que te pide el usuario → dilo antes de programar, no después.
- Si un requisito es **ambiguo** → pregunta. No asumas.

---

## 3. Durante la tarea

- **Bug o trampa descubierta** → anótala; irá a \`${byId.lessons.filename}\` al cerrar.
- **Decisión de arquitectura** → anótala; irá a la Bitácora de \`${byId.plan.filename}\`.
- **No** edites los archivos maestros a mitad de tarea salvo que la tarea sea precisamente esa.

---

## 4. Al terminar — ESCRIBIR en el orden sagrado

${writeFiles.map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.purpose}`).join('\n')}

> ${spec.writeOrderRationale}

### Formato de lección (\`${byId.lessons.filename}\` → ${spec.entries.lesson.section})

${entryBlock(spec.entries.lesson, 'es')}

### Formato de decisión (\`${byId.plan.filename}\` → ${spec.entries.decision.section})

${entryBlock(spec.entries.decision, 'es')}

### Formato de mina activa (\`${byId.lessons.filename}\` → ${spec.entries.mine.section})

${table(spec.entries.mine.table.columns, [
  ['[Componente]', '[Qué rompe y cuándo]', spec.entries.mine.table.states.map((s) => `${s.emoji} ${s.label}`).join(' / ')],
])}

${spec.entries.mine.table.states.map((s) => `- ${s.emoji} **${s.label}** — ${s.meaning}`).join('\n')}

### Formato de fecha — obligatorio

Todas las fechas usan **${d.display}** (ISO 8601). Ejemplo: \`${d.example}\`.
${d.rationale}

---

## 5. Fase Cero (si falta algún archivo maestro)

Haz estas preguntas, una por una, y espera la respuesta:

${spec.init.tokens
  .filter((t) => t.question)
  .map((t, i) => `${i + 1}. ${t.question}`)
  .join('\n')}

Con las respuestas, crea los archivos que falten con las secciones de la sección 1.
**Nunca** los crees vacíos ni inventes datos del proyecto.

---

## 6. Regla de interconexión

Los tres archivos son **un solo organismo**, no tres documentos sueltos:

- Decisión de diseño en \`${byId.plan.filename}\` → refléjala en \`${byId.dna.filename}\`.
- Trampa técnica al implementar → crúzala en \`${byId.lessons.filename}\`.
- Cambio de stack → ADN + bitácora + lección (si aplica).

Una entrada que no enlaza con las otras dos es una entrada huérfana: **el tridente se desincroniza justo ahí**.

---

## 7. Verificación

Antes de dar por cerrada una tarea que tocó los archivos maestros, comprueba a mano:

- [ ] Los ${spec.files.length} archivos existen y conservan todas sus secciones.
- [ ] Toda entrada nueva lleva fecha en \`${d.display}\` y **todos** sus campos.
- [ ] Cada entrada enlaza con los otros dos archivos cuando corresponde.
- [ ] Ninguna decisión del plan contradice una regla del ADN.

---

## 8. Compatibilidad entre herramientas

Este archivo es la **única fuente** de estas instrucciones. El resto de archivos de
configuración de agentes de este proyecto son punteros que reenvían aquí; si los
editas, edita este archivo en su lugar.

${adapterTable('es')}

---

*${spec.protocol.name} v${spec.protocol.version} — ${spec.protocol.repository}*
`;
}

// ------------------------- manifiestos para los scripts de inicialización

/**
 * Los scripts de init necesitan la lista de archivos maestros y el mapa de
 * adaptadores. Tenerla escrita en cada script era una segunda y tercera fuente
 * de verdad; ahora se genera aquí y los scripts la cargan.
 */
function buildManifestSh() {
  const asked = spec.init.tokens.filter((t) => t.question);
  const masters = spec.files.map((f) => f.filename);
  const ad = spec.adapters.filter((a) => a.kind !== 'native' || a.path === 'AGENTS.md');
  const seen = new Set();
  const keys = [];
  const paths = [];
  for (const a of ad) {
    if (seen.has(a.path)) continue;
    seen.add(a.path);
    keys.push(a.key);
    paths.push(a.path);
  }
  return `#!/usr/bin/env bash
# ${HDR_OPEN.slice(5, -4).trim()}
# GENERADO POR scripts/sync.mjs — NO EDITAR A MANO.
# Fuente de verdad: protocol/tridente.spec.json
# ${HDR_CLOSE.slice(5, -4).trim()}
#
# Datos del protocolo para init-tridente.sh. Se carga con 'source'.
#
# shellcheck disable=SC2034
# Todas estas variables las consume init-tridente.sh, que hace source de este
# archivo. ShellCheck analiza cada archivo por separado y no puede verlo, así
# que las daría por no usadas.

TRIDENTE_VERSION="${spec.protocol.version}"
TRIDENTE_DATE_FORMAT="+%Y-%m-%d"

# Archivos maestros, en orden de lectura.
TRIDENTE_MASTERS=(${masters.map((m) => `"${m}"`).join(' ')})

# Rol de cada archivo maestro, para el resumen final (mismo orden).
TRIDENTE_ROLES=(${spec.files.map((f) => `"${f.emoji} ${f.role}"`).join(' ')})

# Tokens sustituibles en las plantillas.
TRIDENTE_TOKENS=(${spec.init.tokens.map((t) => `"${t.token}"`).join(' ')})

# Entrevista de la Fase Cero: sólo los tokens que se preguntan (arrays paralelos).
TRIDENTE_ASK_TOKENS=(${asked.map((t) => `"${t.token}"`).join(' ')})
TRIDENTE_ASK_QUESTIONS=(${asked.map((t) => `"${t.question}"`).join(' ')})
TRIDENTE_ASK_HINTS=(${asked.map((t) => `"${t.hint ?? ''}"`).join(' ')})

# Adaptadores: clave corta -> ruta (arrays paralelos, mismo índice).
TRIDENTE_ADAPTER_KEYS=(${keys.map((k) => `"${k}"`).join(' ')})
TRIDENTE_ADAPTER_PATHS=(${paths.map((p) => `"${p}"`).join(' ')})
`;
}

function buildManifestPs() {
  const asked = spec.init.tokens.filter((t) => t.question);
  const ad = spec.adapters.filter((a) => a.kind !== 'native' || a.path === 'AGENTS.md');
  const seen = new Set();
  const pairs = [];
  for (const a of ad) {
    if (seen.has(a.path)) continue;
    seen.add(a.path);
    pairs.push([a.key, a.path]);
  }
  return `# ${HDR_OPEN.slice(5, -4).trim()}
# GENERADO POR scripts/sync.mjs — NO EDITAR A MANO.
# Fuente de verdad: protocol/tridente.spec.json
# ${HDR_CLOSE.slice(5, -4).trim()}
#
# Datos del protocolo para init-tridente.ps1. Se carga con dot-sourcing.

$TridenteVersion = '${spec.protocol.version}'
$TridenteDateFormat = 'yyyy-MM-dd'

# Archivos maestros, en orden de lectura.
$TridenteMasters = @(${spec.files.map((f) => `'${f.filename}'`).join(', ')})

# Rol de cada archivo maestro, para el resumen final (mismo orden).
$TridenteRoles = @(${spec.files.map((f) => `'${f.emoji} ${f.role}'`).join(', ')})

# Tokens sustituibles en las plantillas.
$TridenteTokens = @(${spec.init.tokens.map((t) => `'${t.token}'`).join(', ')})

# Entrevista de la Fase Cero: sólo los tokens que se preguntan.
$TridenteAsk = @(
${asked
  .map((t) => `    @{ Token = '${t.token}'; Question = '${t.question.replace(/'/g, "''")}'; Hint = '${(t.hint ?? '').replace(/'/g, "''")}' }`)
  .join('\n')}
)

# Adaptadores: clave corta -> ruta.
$TridenteAdapters = [ordered]@{
${pairs.map(([k, p]) => `    '${k}' = '${p}'`).join('\n')}
}
`;
}

// ------------------------------------------------- bloques dentro del README

/** Diagrama mermaid del Tridente, con los nombres reales del spec. */
function tridentGraph(lang = 'es') {
  const en = lang === 'en';
  // Todo se deriva del spec: añadir o renombrar un archivo maestro no puede
  // producir un nodo `undefined` en el diagrama.
  // #74aa9c está reservado para el nodo CODE: no debe repetirse en un maestro.
  const PALETTE = ['#8E75B2', '#00FFFF', '#FF006E', '#f4a261', '#a3b18a', '#e07a5f'];
  const nodeId = (f) => f.id.toUpperCase().replace(/[^A-Z0-9]/g, '');
  const color = (i) => PALETTE[i % PALETTE.length];
  const colorOf = Object.fromEntries(spec.files.map((f, i) => [f.id, color(i)]));

  const nodes = spec.files
    .map((f) => `        ${nodeId(f)}["${f.emoji} ${f.filename}<br/><i>${en ? f.roleEn : f.role}</i>"]`)
    .join('\n');
  const reads = readFiles
    .map((f, i) => `    AGENT -->|"${i + 1}. ${en ? 'Always read' : 'Lee siempre'}"| ${nodeId(f)}`)
    .join('\n');
  const writes = spec.writeOrder
    .slice(0, -1)
    .map((id, i) => {
      const next = byId[spec.writeOrder[i + 1]];
      const label = en ? `Update ${i + 1}` : `Actualiza ${i + 1}.º`;
      return `    ${nodeId(byId[id])} -.->|"${label}"| ${nodeId(next)}`;
    })
    .join('\n');
  const styles = spec.files
    .map((f) => `    style ${nodeId(f)} fill:#1a1a2e,stroke:${colorOf[f.id]},color:#fff`)
    .join('\n');
  return `\`\`\`mermaid
graph TB
    subgraph TRIDENT["🔱 ${en ? spec.protocol.nameEn : spec.protocol.name}"]
${nodes}
    end

    AGENT["🤖 ${en ? 'AI Agent' : 'Agente de IA'}"]
    CODE["💻 ${en ? 'Project Code' : 'Código del Proyecto'}"]

${reads}
    AGENT -->|"${spec.files.length + 1}. ${en ? 'Write with context' : 'Escribe con contexto'}"| CODE

${writes}

${styles}
    style AGENT fill:#0d0d0d,stroke:#fff,color:#fff
    style CODE fill:#0d0d0d,stroke:#74aa9c,color:#fff
\`\`\``;
}

/** Las tres tarjetas en HTML, una por archivo maestro. */
function tridentCards(lang = 'es') {
  const en = lang === 'en';
  const width = Math.floor(100 / spec.files.length);
  const cells = spec.files
    .map(
      (f) => `<td width="${width}%" valign="top">

### ${f.emoji} \`${f.filename}\`
**${en ? f.roleEn : f.role}**

${en ? f.purposeEn : f.purpose}

</td>`,
    )
    .join('\n');
  return `<table>\n<tr>\n${cells}\n</tr>\n</table>`;
}

/** Bloques inyectados entre marcadores <!-- tridente:begin:ID --> … end. */
function injectedBlocks() {
  return {
    'trident-table': tridentTable('es'),
    'trident-table-en': tridentTable('en'),
    'trident-graph': tridentGraph('es'),
    'trident-graph-en': tridentGraph('en'),
    'trident-cards': tridentCards('es'),
    'trident-cards-en': tridentCards('en'),
    'quickstart-result': `El script hace ${spec.init.tokens.filter((t) => t.question).length} preguntas y genera ${spec.files
      .map((f) => `\`${f.filename}\``)
      .join(', ')
      .replace(/, ([^,]*)$/, ' y $1')} poblados, más \`AGENTS.md\` y los punteros de cada herramienta.`,
    'security-files': `Un agente trata ${spec.files
      .map((f) => `\`${f.filename}\``)
      .join(', ')
      .replace(/, ([^,]*)$/, ' y $1')} como reglas del proyecto. Quien pueda escribir en ellos puede **redirigir el comportamiento del agente**.`,
    'compat-table': adapterTable('es'),
    'compat-table-en': adapterTable('en'),
    'install-table': installTable('es'),
    'install-table-en': installTable('en'),
    'read-order': readFiles
      .map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.extract}`)
      .join('\n'),
    'write-order': writeFiles
      .map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.purpose}`)
      .join('\n'),
    'write-order-en': writeFiles
      .map((f, i) => `${i + 1}. **\`${f.filename}\`** — ${f.purposeEn}`)
      .join('\n'),
    'date-format': `Todas las fechas de los archivos maestros usan **${spec.dateFormat.display}** (ISO 8601), por ejemplo \`${spec.dateFormat.example}\`. ${spec.dateFormat.rationale}`,
    'date-format-en': `All dates in the master files use **${spec.dateFormat.display}** (ISO 8601), e.g. \`${spec.dateFormat.example}\`.`,
    // Esta nota tiene que nombrar el archivo del ADN para explicar la colisión,
    // así que se genera en vez de escribirse a mano.
    'gemini-note':
      `> **Nota sobre Gemini:** no se genera \`GEMINI.md\` en la raíz. En Windows y macOS el ` +
      `sistema de archivos no distingue mayúsculas, así que \`GEMINI.md\` y \`${byId.dna.filename}\` ` +
      `(el ADN) serían **el mismo archivo**. En su lugar se configura \`.gemini/settings.json\` ` +
      `para que Gemini CLI cargue \`AGENTS.md\` y \`${byId.dna.filename}\` como contexto.`,
    'gemini-note-en':
      `> **On Gemini:** no \`GEMINI.md\` is generated at the root. On Windows and macOS the ` +
      `filesystem is case-insensitive, so \`GEMINI.md\` and \`${byId.dna.filename}\` (the DNA file) ` +
      `would be **the same file**. Instead, \`.gemini/settings.json\` tells Gemini CLI to load ` +
      `\`AGENTS.md\` and \`${byId.dna.filename}\` as context.`,
  };
}

/** Sustituye el contenido entre marcadores. Devuelve el texto nuevo. */
export function injectBlocks(text, blocks) {
  let out = text;
  for (const [id, body] of Object.entries(blocks)) {
    const re = new RegExp(
      `(<!--\\s*tridente:begin:${id}\\s*-->)[\\s\\S]*?(<!--\\s*tridente:end:${id}\\s*-->)`,
      'g',
    );
    // Reemplazo con función para que `$` dentro del cuerpo no se interprete.
    out = out.replace(re, (_m, open, close) => `${open}\n${body}\n${close}`);
  }
  return out;
}

/** IDs de marcador presentes en un texto. */
export function markerIds(text) {
  return [...text.matchAll(/<!--\s*tridente:begin:([\w-]+)\s*-->/g)].map((m) => m[1]);
}

// ------------------------------------------------------------------ ejecución

const drift = [];
let written = 0;

function emit(relPath, content) {
  const abs = join(ROOT, relPath);
  const next = norm(content);
  const prev = existsSync(abs) ? norm(readFileSync(abs, 'utf8').replace(/^﻿/, '')) : null;
  if (prev === next) return;
  if (CHECK) {
    drift.push({ path: relPath, reason: prev === null ? 'falta' : 'desincronizado' });
    return;
  }
  mkdirSync(dirname(abs), { recursive: true });
  // Windows PowerShell 5.1 lee los .ps1 como ANSI si no llevan BOM UTF-8:
  // sin él, los acentos de las preguntas llegan corrompidos al usuario.
  const onDisk = relPath.endsWith('.ps1') ? '﻿' + next.replace(/\n/g, '\r\n') : next;
  writeFileSync(abs, onDisk, 'utf8');
  written++;
  console.log(`  ${prev === null ? '+' : '~'} ${relPath}`);
}

const outputs = {
  'AGENTS.md': buildAgents(),
  'docs/AGENTS.en.md': buildAgentsEn(),
  'dist/AGENTS.md': buildProjectAgents(),
  'SKILL.md': buildSkill(),
  ...Object.fromEntries(spec.files.map((f) => [`templates/${f.filename}`, buildTemplate(f)])),
  'templates/README.md': buildTemplatesReadme(),
  'protocol/manifest.sh': buildManifestSh(),
  'protocol/manifest.ps1': buildManifestPs(),
  ...buildAdapters(),
};

console.log(CHECK ? 'Verificando sincronización…' : 'Regenerando artefactos desde el SSOT…');
for (const [p, c] of Object.entries(outputs)) emit(p, c);

// Documentos escritos a mano con bloques inyectados.
const blocks = injectedBlocks();
for (const [file, required] of Object.entries(spec.injectedBlocks ?? {})) {
  const abs = join(ROOT, file);
  if (!existsSync(abs)) {
    drift.push({ path: file, reason: 'declarado en spec.injectedBlocks pero no existe' });
    continue;
  }
  const src = readFileSync(abs, 'utf8');
  const present = markerIds(src);

  const unknown = present.filter((id) => !(id in blocks));
  if (unknown.length) {
    drift.push({ path: file, reason: `marcador desconocido: ${unknown.join(', ')}` });
  }

  // Un marcador borrado a mano desactivaría la anti-deriva en silencio: los
  // bloques obligatorios de cada documento se declaran en el spec y se exigen.
  const missing = required.filter((id) => !present.includes(id));
  if (missing.length) {
    drift.push({ path: file, reason: `falta(n) bloque(s) obligatorio(s): ${missing.join(', ')}` });
  }

  emit(file, injectBlocks(src, blocks));
}

// Un marcador inventado en un archivo que no está en injectedBlocks sería una
// zona franca: parece sincronizada y nadie la regenera. Se caza en todos los
// documentos escritos a mano, no sólo en los tres declarados.
{
  const declaredFiles = new Set(Object.keys(spec.injectedBlocks ?? {}));
  const generatedFiles = new Set(spec.generated);
  const scan = (dir, depth = 0) => {
    if (depth > 3) return;
    for (const e of readdirSync(join(ROOT, dir || '.'), { withFileTypes: true })) {
      if (['.git', 'node_modules', 'jules_session', 'GCP_Proyectos'].includes(e.name)) continue;
      const rel = dir ? `${dir}/${e.name}` : e.name;
      if (e.isDirectory()) {
        scan(rel, depth + 1);
        continue;
      }
      if (!e.name.endsWith('.md') || declaredFiles.has(rel) || generatedFiles.has(rel)) continue;
      const text = readFileSync(join(ROOT, rel), 'utf8');
      // Sólo cuentan los pares begin/end completos: CONTRIBUTING.md documenta
      // la sintaxis citando un `begin` suelto y eso no es un bloque.
      const ids = markerIds(text).filter((id) =>
        new RegExp(`<!--\\s*tridente:end:${id}\\s*-->`).test(text),
      );
      if (ids.length) {
        // Un id inventado sería una zona franca: parece un bloque sincronizado,
        // nadie lo regenera y la prosa de dentro queda fuera de todo control.
        const unknown = ids.filter((id) => !(id in blocks));
        drift.push({
          path: rel,
          reason: unknown.length
            ? `marcador desconocido (${unknown.join(', ')}) en un archivo fuera de spec.injectedBlocks`
            : `usa marcadores (${ids.join(', ')}) pero no está en spec.injectedBlocks`,
        });
      }
    }
  };
  scan('');
}

// Comprobación cruzada en los dos sentidos entre spec.generated y lo emitido.
const declared = new Set(spec.generated);
for (const g of spec.generated) {
  if (!existsSync(join(ROOT, g)) && !(g in outputs)) {
    drift.push({ path: g, reason: 'declarado en spec.generated pero no generado' });
  }
}
for (const p of Object.keys(outputs)) {
  if (!declared.has(p)) {
    drift.push({ path: p, reason: 'generado pero ausente de spec.generated' });
  }
}

// Huérfanos: un .md en templates/ que ya no corresponde a ningún archivo del
// spec seguiría copiándose al proyecto del usuario como si fuera maestro.
const tplDir = join(ROOT, 'templates');
if (existsSync(tplDir)) {
  const legit = new Set([...spec.files.map((f) => f.filename), 'README.md']);
  for (const name of readdirSync(tplDir)) {
    if (!name.endsWith('.md') || legit.has(name)) continue;
    drift.push({ path: `templates/${name}`, reason: 'huérfano: no corresponde a ningún archivo del spec' });
  }
}

// Punteros fantasma: quitar una herramienta del spec dejaba su archivo en el
// disco. Ningún script lo copia ya y la documentación no lo menciona, pero ahí
// sigue. Se detecta por la marca de archivo generado.
{
  const known = new Set([...Object.keys(outputs), ...spec.generated, ...Object.keys(spec.injectedBlocks ?? {})]);
  const MARK_JSON = 'Puntero del Tridente de Memoria';

  /** ¿Es este archivo un artefacto que generó este script alguna vez? */
  const looksGenerated = (rel) => {
    const text = readFileSync(join(ROOT, rel), 'utf8');
    if (rel.endsWith('.json')) return text.includes(MARK_JSON);
    // La cabecera cuenta sólo si está en el preámbulo: un .mdc la lleva tras su
    // frontmatter YAML, y un documento que la cita como ejemplo (CONTRIBUTING.md)
    // la tiene mucho más abajo y no es un artefacto.
    return text.split('\n').slice(0, 12).join('\n').includes(HDR_OPEN);
  };

  const sweep = (dir, depth = 0) => {
    if (depth > 3) return;
    for (const e of readdirSync(join(ROOT, dir || '.'), { withFileTypes: true })) {
      if (['.git', 'node_modules', 'jules_session', 'GCP_Proyectos', 'templates'].includes(e.name)) continue;
      const rel = dir ? `${dir}/${e.name}` : e.name;
      if (e.isDirectory()) {
        sweep(rel, depth + 1);
        continue;
      }
      if (known.has(rel)) continue;
      // Los punteros no siempre tienen extensión (.windsurfrules).
      const candidate = /\.(md|mdc|json)$/.test(e.name) || !e.name.slice(1).includes('.');
      if (candidate && looksGenerated(rel)) {
        drift.push({ path: rel, reason: 'artefacto generado que ya no declara el spec' });
      }
    }
  };
  sweep('');
}

// Invariante de rutas: ninguna ruta de adaptador puede ser un directorio padre
// de otra (p. ej. .clinerules como archivo y .clinerules/ como carpeta).
{
  const paths = [...new Set(spec.adapters.map((a) => a.path))];
  for (const a of paths) {
    for (const b of paths) {
      if (a !== b && b.startsWith(a + '/')) {
        drift.push({ path: a, reason: `colisiona con ${b}: no puede ser archivo y directorio a la vez` });
      }
    }
  }
}

if (CHECK) {
  if (drift.length) {
    console.error(`\n✗ ${drift.length} archivo(s) desincronizado(s):`);
    for (const d of drift) console.error(`  - ${d.path} (${d.reason})`);
    console.error('\nEjecuta: node scripts/sync.mjs');
    process.exit(1);
  }
  console.log('✓ Toda la documentación derivada está sincronizada con el SSOT.');
} else {
  console.log(written ? `\n✓ ${written} archivo(s) actualizado(s).` : '\n✓ Ya estaba todo sincronizado.');
}
